### ISSUE TITLE
没有显示校验

### ISSUE THREAD

**Issue by cindy3124** [FuckyouBB/extent_report_template_httprunner2#2]
使用默认模板的校验：
![image](https://user-images.githubusercontent.com/26869514/86423881-8749a400-bd13-11ea-8402-b2129cd97859.png)

使用新模板的校验：
![image](https://user-images.githubusercontent.com/26869514/86423947-c1b34100-bd13-11ea-9987-95b37deddfb9.png)

结果：新模板没有显示校验内容

**Comment by FuckyouBB** [comment]
fix
